source("scripts/01_setup.R")
source("scripts/02_read_and_parse_wos.R")
source("scripts/03_apply_corrections.R")
source("scripts/04_build_intellectual_base.R")
source("scripts/05_overlap_matrix.R")
source("scripts/06_bibliographic_coupling.R")
source("scripts/07_tables_and_plots.R")
source("scripts/08_session_log.R")
cat("=== Done ===\n")
